spring:
  kafka:
    bootstrap-servers: localhost:9092  # ??? ??? ?? ?? ?? [3][5][8]
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # ??? ? ??? ?? [3]
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # ??? ? ??? ?? [3]
    consumer:
      group-id: my-group  # ??? ?? ID [3][5]
      auto-offset-reset: earliest # ??? ??? ?? ? ?? ?? (earliest: ????, latest: ????) [3][5]
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # ??? ? ???? ??
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # ??? ? ???? ??
